
<?php

namespace Tests\Feature;

use Tests\TestCase;

class GenerateSawDrawingForBatchPicklistTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_generate_saw_drawing()
    {
        // Given

        // When

        // Then

    }
}
